luci-app-netspeedtest: update baidu sk

diff --git a/luci-app-netspeedtest/root/usr/lib/netspeedtest/speedtest b/luci-app-netspeedtest/root/usr/lib/netspeedtest/speedtest
--- a/luci-app-netspeedtest/root/usr/lib/netspeedtest/speedtest
+++ b/luci-app-netspeedtest/root/usr/lib/netspeedtest/speedtest
@@ -6,35 +6,53 @@ export HOME='/etc/speedtest'
 SPEEDTEST_CLI='/usr/bin/speedtest'
 SPEEDTEST_RESULT='/etc/speedtest/speedtest_result'
 
-[ -n "$(pgrep -f "$SPEEDTEST_CLI")" ] && exit 1
+pgrep -fx "$SPEEDTEST_CLI" && exit 1
 
-LOCAL_IP=$(curl -s -4 --connect-timeout 3 http://ip.3322.net)
+LOCAL_IP=$(curl -s -4 --connect-timeout 3 http://ip.3322.net || echo "")
 
-BAIDU_SK="LHHGlmhcb4ENvIXpR9QQ2tBYa6ooUowX hYCENCEx1nXO0Nt46ldexfG9oI49xBGh 0kKZnWWhXEPfzIkklmzAa3dZ"
-if [ -n "$LOCAL_IP" ]; then
-	for SK in $BAIDU_SK
-	do
-		INFO=$(curl -sk --connect-timeout 3 "https://api.map.baidu.com/location/ip?ip="$LOCAL_IP"&coor=bd09ll&ak=$SK")
-		if [ "$(echo $INFO | jsonfilter -e "@['status']")" = 0 ]; then
-			status=0
-			break
-		fi
-	done
-	if [ "$status" = 0 ]; then
-		lon=$(echo $INFO | jsonfilter -e "@['content']['point']['x']")
-		lat=$(echo $INFO | jsonfilter -e "@['content']['point']['y']")
-		server_id=$(curl -sk --connect-timeout 3 "https://www.speedtest.net/api/ios-config.php?lon=$lon&lat=$lat" | grep "server url" | head -n1 | sed 's/.*id="//;s/".*//')
-		[ -n "$server_id" ] && ARG="-s $server_id"
-	fi
+BAIDU_SK=(
+    "0kKZnWWhXEPfzIkklmzAa3dZ"
+    "3GGtGlCtbAGa1GYK70XFX2Rb"
+    "08fadd5a7e397b10f4599c325ee55b9c"
+    "8139d029b1608c4f6f6ff182318debb5"
+    "CDa36173b7623105124eaf21e6c07569"
+    "Er8iGG4UMfSd3Ckuc6w8C56peI4ge1Ih"
+    "fepE9S7tmruLPt5Z6vqNCNzRk1n9EGe8"
+    "hYCENCEx1nXO0Nt46ldexfG9oI49xBGh"
+    "odPxy2gZZ8ABQizuNkZvhUshjIwtml98"
+    "R6l3LOp0hMYGpxw0nZGHXWymNP9Y6kIH"
+    "yG5PPp07M54yW2Qb1ZUIXhjR22V13TOw"
+)
+
+status=1
+arg=""
+if [[ -n "$LOCAL_IP" ]]; then
+    for SK in "${BAIDU_SK[@]}"; do
+        INFO=$(curl -sk --connect-timeout 3 "https://api.map.baidu.com/location/ip?ip=$LOCAL_IP&coor=bd09ll&ak=$SK")
+        if [[ "$(echo "$INFO" | jsonfilter -e "@['status']")" = 0 ]]; then
+            status=0
+            break
+        fi
+    done
+    if [[ "$status" = 0 ]]; then
+        lon=$(echo "$INFO" | jsonfilter -e "@['content']['point']['x']")
+        lat=$(echo "$INFO" | jsonfilter -e "@['content']['point']['y']")
+        server_id=$(curl -sk --connect-timeout 3 "https://www.speedtest.net/api/ios-config.php?lon=$lon&lat=$lat" | grep 'server url' | head -n1 | sed 's/.*id="//;s/".*//')
+        [[ -n "$server_id" ]] && arg="-s $server_id"
+    fi
 fi
 
 echo "Testing" > "$SPEEDTEST_RESULT"
 
-RUNTEST=$($SPEEDTEST_CLI --accept-gdpr --accept-license --progress=no $ARG 2>&1)
-if [ $(echo $RUNTEST | grep -c "No servers defined") -ge 1 ] || [ $(echo $RUNTEST | grep -c "error") -ge 1 ]; then
-	RUNTEST=$($SPEEDTEST_CLI --accept-gdpr --accept-license --progress=no 2>&1)
+RUNTEST=$($SPEEDTEST_CLI --accept-gdpr --accept-license --progress=no $arg 2>&1 || true)
+if echo "$RUNTEST" | egrep -q "No servers defined|error"; then
+    RUNTEST=$($SPEEDTEST_CLI --accept-gdpr --accept-license --progress=no 2>&1 || true)
 fi
 
 RESULT=$(echo "$RUNTEST" | grep "Result URL" | awk '{print $NF}')
 
-[ -n "$RESULT" ] && echo "$RESULT" > "$SPEEDTEST_RESULT" || echo "Test failed" > "$SPEEDTEST_RESULT"
+if [[ "$RESULT" =~ ^https?:// ]]; then
+    echo "$RESULT" > "$SPEEDTEST_RESULT"
+else
+    echo "Test failed" > "$SPEEDTEST_RESULT"
+fi
