luci-app-netspeedtest: speedtest: optimize speed measurement node
Signed-off-by: sbwml <admin@cooluc.com>

diff --git a/luci-app-netspeedtest/root/usr/lib/netspeedtest/speedtest b/luci-app-netspeedtest/root/usr/lib/netspeedtest/speedtest
--- a/luci-app-netspeedtest/root/usr/lib/netspeedtest/speedtest
+++ b/luci-app-netspeedtest/root/usr/lib/netspeedtest/speedtest
@@ -1,12 +1,38 @@
 #!/bin/sh
 
+export HOME=/root
 SPEEDTEST_CLI='/usr/bin/speedtest'
 SPEEDTEST_RESULT='/var/speedtest_result'
 
-command="$SPEEDTEST_CLI --accept-gdpr --accept-license --progress=no"
+[ -n "$(pgrep -f "$SPEEDTEST_CLI")" ] && return 1
 
-[ -n "$(pgrep -f "$command")" ] && return 1
+LOCAL_IP=$(curl -s -4 --connect-timeout 3 http://ip.3322.net)
+
+BAIDU_SK="LHHGlmhcb4ENvIXpR9QQ2tBYa6ooUowX hYCENCEx1nXO0Nt46ldexfG9oI49xBGh 0kKZnWWhXEPfzIkklmzAa3dZ"
+if [ -n "$LOCAL_IP" ]; then
+	for SK in $BAIDU_SK
+	do
+		INFO=$(curl -sk --connect-timeout 3 "https://api.map.baidu.com/location/ip?ip="$LOCAL_IP"&coor=bd09ll&ak=$SK")
+		if [ "$(echo $INFO | jsonfilter -e "@['status']")" = 0 ]; then
+			status=0
+			break
+		fi
+	done
+	if [ "$status" = 0 ]; then
+		lon=$(echo $INFO | jsonfilter -e "@['content']['point']['x']")
+		lat=$(echo $INFO | jsonfilter -e "@['content']['point']['y']")
+		server_id=$(curl -sk "https://www.speedtest.net/api/ios-config.php?lon=$lon&lat=$lat" | grep "server url" | head -n1 | sed 's/.*id="//;s/".*//')
+		ARG="-s $server_id"
+	fi
+fi
 
 echo "Testing" > "$SPEEDTEST_RESULT"
-result=$($command | grep 'www.speedtest.net/result/' | awk '{print $3}')
-[ -n "$result" ] && echo "$result" > "$SPEEDTEST_RESULT" || echo "Test failed" > "$SPEEDTEST_RESULT"
+
+RUNTEST=$($SPEEDTEST_CLI --accept-gdpr --accept-license --progress=no $ARG 2>&1)
+if [ $(echo $RUNTEST | grep -c "No servers defined") -ge 1 ] || [ $(echo $RUNTEST | grep -c "error") -ge 1 ]; then
+	RUNTEST=$($SPEEDTEST_CLI --accept-gdpr --accept-license --progress=no 2>&1)
+fi
+
+RESULT=$(echo "$RUNTEST" | grep "Result URL" | awk '{print $NF}')
+
+[ -n "$RESULT" ] && echo "$RESULT" > "$SPEEDTEST_RESULT" || echo "Test failed" > "$SPEEDTEST_RESULT"
